# Generated by Django 5.2.17 on 2026-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.BigIntegerField()),
                ('truncation', models.FloatField(default=0.8)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-likes', '-created_at'],
                'indexes': [models.Index(fields=['-likes', '-created_at'], name='gallery_gen_likes_c8aeb5_idx')],
                'constraints': [models.UniqueConstraint(fields=('seed', 'truncation'), name='unique_seed_truncation')],
            },
        ),
    ]
